name: hello world

on:
  push:
    branches: [ main, Selenium ]
  pull_request:
    branches: [ main, Selenium ]

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      - name: Hello Step
        run: echo "Hello World"